from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('index.html', views.index, name = 'index'),
    path('login.html', views.login_html, name = 'login_html'),
    path('no_login.html', views.no_login_html, name = 'no_login_html'),
    path('signup.html', views.signup_html, name = 'signup_html'),
    path('main.html', views.main_html, name = 'main_html'),
    path('cart.html', views.cart_html, name = 'cart_html'),
    path('edit_order.html', views.edit_order_html, name = 'edit_order_html'),
    path('aux_get_user_info', views.aux_get_user_info, name = 'aux_get_user_info'),
    path('catalog.html', views.catalog_html, name = 'catalog_html'),
    path('orders.html', views.orders_html, name = 'orders_html'),
    path('catalog', views.catalog, name = 'catalog'),
    path('orders', views.orders, name = 'orders'),
    path('cart', views.cart, name = 'cart'),
    path('logout', views.logout, name = 'logout'),
    path('login/<str:username>/<str:password>', views.login, name = 'login'),
    path('signup/<str:username>/<str:password>/<str:email>', views.signup, name = 'signup'),   
    path('account.html', views.account_html, name = 'account_html'),
    path('search/<str:name>', views.search, name = 'search'),   
    path('buy/<int:product_id>', views.buy, name = 'buy'),   
    path('remove_from_cart/<int:order_id>', views.remove_from_cart, name = 'remove_from_cart'),   
    path('edit/<int:order_id>', views.edit, name = 'edit'),   
    path('rate/<int:order_id>/<int:rating>', views.rate, name = 'rate'),   
    path('post/<int:product_id>/<str:comment>', views.post, name = 'post'),   
    path('confirm.html', views.confirm_html, name = 'confirm_html'),   
    path('aux_get_buy_info', views.aux_get_buy_info, name = 'aux_get_buy_info'),   
    path('aux_get_order_info', views.aux_get_order_info, name = 'aux_get_order_info'),   
    path('aux_get_comments', views.aux_get_comments, name = 'aux_get_comments'),   
    path('confirm/<int:product_id>/<int:amount>/<int:address_x>/<int:address_y>/<str:ups_account_name>', views.confirm, name = 'confirm'),   
    path('add/<int:product_id>/<int:amount>/<int:address_x>/<int:address_y>/<str:ups_account_name>', views.add, name = 'add'),   
    path('change_order_info/<int:order_id>/<int:amount>/<int:address_x>/<int:address_y>/<str:ups_account_name>', views.change_order_info, name = 'change_order_info'),   
    path('change_user_info/<str:password>/<str:email>', views.change_user_info, name = 'change_user_info'),
    path('checkout/<str:order_id_strs>', views.checkout, name = 'checkout'),
]
