# Generated by Django 4.0.1 on 2022-04-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_order_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Oreo', max_length=100),
            preserve_default=False,
        ),
    ]
