# Generated by Django 4.0.1 on 2022-04-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='Good Good', max_length=100),
            preserve_default=False,
        ),
    ]
