# Generated by Django 4.0.1 on 2022-04-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ups_account_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
