# Generated by Django 4.0.4 on 2022-04-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_order_ups_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
