# Generated by Django 4.0.4 on 2022-04-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_product_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
