# Generated by Django 4.0.4 on 2022-04-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
